version: '3.9'

services:
  backend:
    build: .
    container_name: backend-app
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/base-template
      REDIS_URL: redis://redis:6379
    volumes: []
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma generate &&
             npm run seed &&
             npm run start:prod"

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: base-template
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  pgdata:
